Repository algosup/2023-2024-project-3-virtual-processor-team-2, pull requests merged in 2024-02, with the labels that each got.

#11 Check line length
  .gitignore
  src/parser.c
  src/parser.h
Labels: enhancement, Code

#12 Parser update and builder implementation
  .vscode/settings.json
  CMakeLists.txt
  src/ast.h
  src/builder.c
  src/builder.h
  src/debug.c
  src/debug.h
  src/iat2.c
  src/iat2.h
  src/parser.c
  src/parser.h
  src/runner.c
  src/runner.h
  src/stringPlus.c
  src/stringPlus.h
  test/test.cc
Labels: enhancement, Code

#13 Parser and builder
  .gitignore
  CMakeLists.txt
  src/ast.h
  src/builder.c
  src/builder.h
  src/debug.c
  src/debug.h
  src/iat2.c
  src/iat2.h
  src/parser.c
  src/parser.h
  src/runner.c
  src/runner.h
  src/stringPlus.c
  src/stringPlus.h
  test/test.cc
Labels: enhancement, Code

#15 Update builder
  CMakeLists.txt
  src/2at2.c
  src/2at2.h
  src/builder.c
  src/builder.h
  src/debug.c
  src/runner.c
  src/runner.h
  test/test.cc
Labels: enhancement, Code

#21 Bin exporter finished
  .gitignore
  CMakeLists.txt
  src/binExporter.c
  src/binExporter.h
  src/builder.c
  src/builder.h
Labels: enhancement, Code

#23 17 isint function negative value
  .gitignore
  CMakeLists.txt
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  documents/QA/code_documentation_template.md
  documents/QA/meetings_reports.md
  documents/QA/test_cases.md
  documents/QA/test_plan.md
  documents/QA/test_reports.md
  documents/communications/minutes_of_meeting_01_16_2024.pdf
  documents/functional/2023-2024 Project 3 Virtual Processor.pdf
  documents/functional/AT2-Assembly-Language-Documentation.md
  documents/functional/Functional Specification Document Template.md
  documents/functional/at2_language_documentation.pdf
  documents/functional/functional_specification_documentation.md
  documents/images/functional_images/interpreter-mockup.png
  documents/images/functional_images/virtual-terminal.png
  documents/images/management/algosup.png
  documents/images/management/github_logo.png
  documents/images/management/linkedin_logo.png
  documents/images/qa_images/progression_graph.png
  documents/images/qa_images/test_case_pattern.png
  documents/images/qa_images/test_report_pattern.png
  documents/images/technical_images/State-Diagram-parserC.jpg
  documents/images/technical_images/archi_interpreter_diagram.jpg
  documents/images/technical_images/data_structure_diagram.jpg
  documents/management/management_artifact.md
  documents/management/weekly_reports/cumulative.md
  documents/management/weekly_reports/week_3.md
  documents/management/weekly_reports/week_4.md
  documents/technical/technical.md
  src/2at2.c
  src/2at2.h
  src/builder.c
  src/builder.h
  src/debug.c
  src/parser.c
  src/parser.h
  src/runner.c
  src/runner.h
  test/test.cc
Labels: bug, enhancement, Code

#22 Dev into main
  .gitignore
  CMakeLists.txt
  src/binExporter.c
  src/binExporter.h
  src/builder.c
  src/builder.h
Labels: enhancement, Code

#35 Documents
  README.md
  SECURITY.md
  documents/QA/test_plan.md
  documents/images/AOP/ico/aop_logo_256px.ico
  documents/images/AOP/png/aop_logo_256px.png
  documents/images/AT2/ico/AT2_logo_256px.ico
  documents/images/AT2/png/AT2_logo_256px.png
  documents/images/IAT2/ico/iat2_logo_256px.ico
  documents/images/IAT2/png/iat2_logo_256px.png
  documents/images/management/algosup.png
  documents/images/management/algosup_light_blue.svg
  documents/images/management/algosup_orange.svg
  documents/images/management/github_dark_logo.png
  documents/images/management/github_light_logo.png
  documents/images/management/github_logo.png
  documents/images/qa_images/progression_graph.png
  documents/images/technical_images/Diagramming 101 (Community) (Copy) (2).png
  documents/images/technical_images/archi_interpreter_diagram.jpg
  documents/images/technical_images/assembler.png
  documents/images/technical_images/data_model.png
  documents/images/technical_images/v-mmu.png
  documents/management/management_artifact.md
  documents/management/weekly_reports/cumulative.md
  documents/management/weekly_reports/week_5.md
  documents/technical/technical.md
Labels: documentation, enhancement

#39 Setup GitHub actions for the dev branch
  .github/workflows/actions_dev.yml
Labels: enhancement, Actions

#40 Setup GitHub actions for the main branch
  .github/workflows/actions_dev.yml
Labels: enhancement, Actions

#48 Builder v2
  CMakeLists.txt
  src/2at2.c
  src/ast.c
  src/ast.h
  src/binExporter.c
  src/binExporter.h
  src/builder.c
  src/builder.h
  src/debug.c
  src/debug.h
  src/error.c
  src/error.h
  src/parser.c
  src/parser.h
  src/stringPlus.c
  src/stringPlus.h
  test/test.cc
Labels: enhancement, Code

#49 Update main following dev last changes
  CMakeLists.txt
  src/2at2.c
  src/ast.c
  src/ast.h
  src/binExporter.c
  src/binExporter.h
  src/builder.c
  src/builder.h
  src/debug.c
  src/debug.h
  src/error.c
  src/error.h
  src/parser.c
  src/parser.h
  src/stringPlus.c
  src/stringPlus.h
  test/test.cc
Labels: enhancement, Code

#51 Bin export v2
  CMakeLists.txt
  src/2at2.c
  src/binExporter.c
  src/binExporter.h
  src/builder.c
  src/parser.c
  src/parser.h
  test/test.cc
Labels: enhancement, Code

#57 Error system
  CMakeLists.txt
  src/2at2.c
  src/ast.c
  src/ast.h
  src/binExporter.c
  src/binExporter.h
  src/builder.c
  src/builder.h
  src/debug.c
  src/debug.h
  src/error.c
  src/error.h
  src/parser.c
  src/parser.h
  src/stringPlus.c
  src/stringPlus.h
  test/test.cc
Labels: enhancement, Code

#59 Bin exporter and error system update
  .gitignore
  CMakeLists.txt
  src/2at2.c
  src/ast.c
  src/ast.h
  src/binExporter.c
  src/binExporter.h
  src/builder.c
  src/builder.h
  src/debug.c
  src/debug.h
  src/error.c
  src/error.h
  src/parser.c
  src/parser.h
  src/stringPlus.c
  src/stringPlus.h
  test/test.aop
  test/test.cc
Labels: enhancement, Code

#64 Virtual processor
  .gitignore
  CMakeLists.txt
  src/2at2.c
  src/error.c
  src/error.h
  src/vProc.c
  src/vProc.h
  src/vTerminal.c
  src/vTerminal.h
  src/vat2.c
  test/aop/0.aop
  test/aop/1.aop
  test/aop/2.aop
  test/aop/3.aop
  test/aop/4.aop
  test/aop/5.aop
  test/aop/6.aop
  test/aop/7.aop
  test/aop/test.aop
  test/test.cc
Labels: enhancement, Code

#67 Correct issue #56
  src/builder.c
  src/parser.c
Labels: enhancement, Code, bug fix

#70 Builder OK
  CMakeLists.txt
  src/2at2.c
  src/ast.c
  src/binExporter.c
  src/builder.c
  src/parser.c
  src/parser.h
  test/test.cc
Labels: enhancement, Code

#71 Assembler finished
  CMakeLists.txt
  src/2at2.c
  src/ast.c
  src/binExporter.c
  src/builder.c
  src/parser.c
  src/parser.h
  test/test.cc
Labels: enhancement, Code

#72 Update Vproc-unit-test branch
  CMakeLists.txt
  src/2at2.c
  src/ast.c
  src/binExporter.c
  src/builder.c
  src/parser.c
  src/parser.h
  src/vProc.c
  src/vProc.h
  test/aop/test.aop
  test/test.cc
Labels: enhancement, Code

#73 Virtual processor and assembler stable version
  CMakeLists.txt
  src/2at2.c
  src/error.c
  src/vProc.c
  src/vProc.h
  src/vTerminal.c
Labels: enhancement, Code

#88 Virtual processor and assembler stable version
  CMakeLists.txt
  src/2at2.c
  src/error.c
  src/vProc.c
  src/vProc.h
  src/vTerminal.c
Labels: enhancement, Code

#91 Add conditional goto
  CMakeLists.txt
  src/2at2.c
  src/ast.c
  src/ast.h
  src/binExporter.c
  src/binExporter.h
  src/builder.c
  src/builder.h
  src/debug.c
  src/error.c
  src/error.h
  src/parser.c
  src/vProc.c
  src/vTerminal.c
  test/test.cc
Labels: enhancement, Code

#96 Add conditional goto
  CMakeLists.txt
  src/2at2.c
  src/ast.c
  src/ast.h
  src/binExporter.c
  src/binExporter.h
  src/builder.c
  src/builder.h
  src/debug.c
  src/error.c
  src/error.h
  src/parser.c
  src/vProc.c
  src/vTerminal.c
  test/test.cc
Labels: enhancement, Code

#101 Correct not parsing
  src/2at2.c
  src/builder.c
  src/parser.c
Labels: Code, bug fix

#111 Add .aop test files
  test/aop/callRet.aop
  test/aop/goto.aop
  test/aop/if_eq.aop
  test/aop/if_gt.aop
  test/aop/if_gte.aop
  test/aop/if_lt.aop
  test/aop/if_lte.aop
  test/aop/if_neq.aop
  test/aop/label.aop
  test/aop/leftShift.aop
  test/aop/leftShiftSymbol.aop
  test/aop/mov.aop
  test/aop/ngr.aop
  test/aop/not.aop
  test/aop/notSymbol.aop
  test/aop/ob1.aop
  test/aop/pushPop.aop
  test/aop/rightShift.aop
  test/aop/rightShiftSymbol.aop
Labels: Code, test

#115 Add .aop test files
  test/aop/callRet.aop
  test/aop/goto.aop
  test/aop/if_eq.aop
  test/aop/if_gt.aop
  test/aop/if_gte.aop
  test/aop/if_lt.aop
  test/aop/if_lte.aop
  test/aop/if_neq.aop
  test/aop/label.aop
  test/aop/leftShift.aop
  test/aop/leftShiftSymbol.aop
  test/aop/mov.aop
  test/aop/ngr.aop
  test/aop/not.aop
  test/aop/notSymbol.aop
  test/aop/ob1.aop
  test/aop/pushPop.aop
  test/aop/rightShift.aop
  test/aop/rightShiftSymbol.aop
Labels: Code, test
